# Generated by Django 5.2.8 on 2025-11-24 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='numero_licencia',
        ),
    ]
