# Generated by Django 5.2.8 on 2025-11-24 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_remove_medico_activo_remove_medico_numero_licencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultorio',
            name='activo',
        ),
    ]
