# Generated by Django 5.2.8 on 2025-11-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_remove_consultorio_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='razon_cancelacion',
        ),
    ]
