# Generated by Django 5.2.8 on 2025-11-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_remove_cita_estado_remove_cita_razon_cancelacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultorio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='especialidad',
            name='descripcion',
        ),
    ]
