# Generated by Django 5.2.8 on 2025-11-16 01:59

import citasmedicas.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[citasmedicas.validators.validar_cedula_ecuador])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('provincia', models.CharField(choices=[('01', 'Azuay'), ('02', 'Bolívar'), ('03', 'Cañar'), ('04', 'Carchi'), ('05', 'Cotopaxi'), ('06', 'Chimborazo'), ('07', 'El Oro'), ('08', 'Esmeraldas'), ('09', 'Guayas'), ('10', 'Imbabura'), ('11', 'Loja'), ('12', 'Los Ríos'), ('13', 'Manabí'), ('14', 'Morona Santiago'), ('15', 'Napo'), ('16', 'Pastaza'), ('17', 'Pichincha'), ('18', 'Tungurahua'), ('19', 'Zamora Chinchipe'), ('20', 'Galápagos'), ('21', 'Sucumbíos'), ('22', 'Orellana'), ('23', 'Santo Domingo'), ('24', 'Santa Elena')], default='17', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[citasmedicas.validators.validar_cedula_ecuador])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('numero_licencia', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], default='INTERNO', max_length=50)),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citasmedicas.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citasmedicas.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citasmedicas.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citasmedicas.consultorio')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citasmedicas.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citasmedicas.paciente')),
            ],
            options={
                'ordering': ['-fecha', 'hora_inicio'],
                'unique_together': {('medico', 'fecha', 'hora_inicio')},
            },
        ),
    ]
