apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-config
  namespace: hospital
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DATABASE_PATH: "/data/db.sqlite3"
  SECRET_KEY: "django-insecure-k8s-local-deployment-secret-key-for-hospital-app"
  SECURE_SSL_REDIRECT: "False"
  SESSION_COOKIE_SECURE: "False"
  CSRF_COOKIE_SECURE: "False"
