# Generated by Django 5.2.8 on 2025-11-16 02:03

import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('medico', 'Médico'), ('admin', 'Administrador')], default='usuario', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, validators=[login.models.validar_cedula_ecuador]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(validators=[login.models.validar_edad]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=15, validators=[login.models.validar_telefono]),
        ),
    ]
