# Generated by Django 5.2.7 on 2026-01-17 01:56

import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_usuario_rol_alter_usuario_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[login.models.validar_cedula_ecuador]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, validators=[login.models.validar_edad]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[login.models.validar_telefono]),
        ),
    ]
